#!/bin/bash
# This script should be sourced to control the shell environment with "cd"

(
    if [[ -d /etc/bash_completeion.d/orchard ]]; then
    read -r -d '' COMPLETION_SCRIPT << EOS
        __orchard()
        {
            local cur prev opts
            COMPREPLY=()
            cur="${COMP_WORDS[COMP_CWORD]}"
            prev="${COMP_WORDS[COMP_CWORD-1]}"
            opts=$(awk -F'=' '{print $2}' $HOME/.orchard/names | tr "\n" " ")

            if [[ ${prev} == "orchard" ]] ; then
                COMPREPLY=( $(compgen -W "${opts}" ${cur}) )
                return 0
            fi
        }
        complete -F __orchard orchard
EOS
else

fi
)

(

    FOLDER_PREFIX="__dir_"
    action=$1
    paths_file="$HOME/.orchard/paths"
    names_file="$HOME/.orchard/names"
    cd_path="$HOME/.orchard/dir_to_cd"

    function __orchard_init_config() {
        if [[ ! -f $paths_file ]]; then
            mkdir -p $HOME/.orchard
            touch $paths_file
            touch $names_file
        fi
    }

    function __orchard_get_folder_id() {
        local folder_name folder_slug folder_id

        folder_name=$1
        folder_slug=$(echo $folder_name | xargs | tr " .-" "_" | tr A-Z a-z)
        folder_id="$FOLDER_PREFIX$folder_slug"

        echo $folder_id
    }

    function __orchard_get_folder_path() {
        local folder_id folder_path

        source $paths_file

        folder_id=$1
        folder_path="${!folder_id}"
        echo $folder_path
    }

    function __orchard_init() {
        local folder_path folder_name folder_id old_path

        folder_path=$(pwd)
        folder_name=$([[ ! -z $1 ]] && echo $1 || basename $folder_path)
        folder_id=$(__orchard_get_folder_id $folder_name)
        old_path=$(__orchard_get_folder_path $folder_id)

        if [[ -z $old_path ]]; then
            echo "$folder_id=$folder_path" >> $paths_file
            echo "$folder_id=$folder_name" >> $names_file
            echo "Creating \"$folder_name\" for path [$folder_path]"
        else
            echo "Fail to create, folder id already exists: $folder_id @ $old_path"
        fi
    }

    function __orchard_write_to_cd() {
        local folder_name folder_id folder_path

        folder_name=$1
        folder_id=$(__orchard_get_folder_id $folder_name)
        folder_path=$(__orchard_get_folder_path $folder_id)

        echo "$folder_path" > $cd_path
    }

    if [[ $action == "init" ]]; then
        __orchard_init
    else
        __orchard_write_to_cd $action
    fi
)


# This is sourced to perform "cd" in the current shell session
if [[ ! $1 == "init" ]]; then
    dir_to_cd=$(cat $HOME/.orchard/dir_to_cd)
    test ! -z $dir_to_cd && cd $dir_to_cd
fi
